spring:
  application:
    name: blood-sample-management-api
  mail:
    host: smtp.gmail.com
    port: 587
    username: {email}
    password: {password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://localhost:3306/bsm_email_db?createDatabaseIfNotExist=true
    username: root
    password: deepak
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
